baseURL = 'https://aahaansingh.github.io/'
languageCode = 'en-us'
title = 'Aahaan Singh'
enableRobotsTXT = true

[module]
  [[module.imports]]
    path = "github.com/michenriksen/hugo-theme-til"

[markup.goldmark.renderer]
  unsafe = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    pageRef = "about/about"
    weight = 10

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    pageRef = "/posts"
    weight = 20

  [[menu.main]]
    identifier = "notes"
    name = "Notes"
    pageRef = "/notes"
    weight = 30

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    pageRef = "/projects"
    weight = 40

  [[menu.main]]
    identifier = "graph"
    name = "Graph"
    pageRef = "/graph"
    weight = 50
    
[params]
  description = "A small collection of things that will hopefully grow."

  [params.author]
    name = "Aahaan Singh"
    email = "aahaansingh@gmail.com"

  [params.footer]
    creativeCommonsLicense = 'by_sa'

  [params.robotstxt]
    blockCC = true
    blockAI = true

[markup]
  [markup.highlight]
    noClasses = false
    style = 'tokyonight-night'

  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true