#+hugo_base_dir: ../

* DONE Posts                                                        
** DONE A Website                                            :@tech:thoughts:
:PROPERTIES:
:EXPORT_FILE_NAME: post1
:EXPORT_DATE: 2025-09-05
:END:

I decided a few weeks back, while interning at Tudor, to create a new website.

The initial reason was that circumstances conspired to make me use a command line editor in order to debug something.
In the second semester of my freshman year, I was forced to use Emacs for a week.
No reason was given.
I did not enjoy this task from above because Emacs felt cumbersome and the commands they gave us were stuff like "move your cursor to the next instance of a character" and "select and copy text".
It makes sense to teach basic commands to someone starting out on an editor, but I was never given a reason why I /should/ use Emacs at all.
Emacs is Emacs because of its huge and, most importantly, extensible[^fn:1] library of modes and commands.
Anyways, I still barely know any Emacs and haven't used it for any big projects yet but I have been using Orgmode semi-regularly and have found it quite useful.

I thought that Orgmode would be a good way to start out with Emacs, and ox-hugo a good way to start out with Orgmode.
I also think that personal websites are cool and that everyone should have one because it's probably the most coherent way in which you can present yourself to the world.

So, we'll see how this goes!

[^fn:1]:  I have yet to grasp elisp, or lisp in general, so the only script I've written is one that replaces a key sequence with an em-dash.

* DONE Projects
:PROPERTIES:
:EXPORT_HUGO_SECTION: projects
:END:


** DONE Batting Collapse                                    :@sports:@tech:cricket:
:PROPERTIES:
:EXPORT_FILE_NAME: proj1
:EXPORT_DATE: 2025-09-05
:END:

I'm a big cricket fan and a pretty terrible player, so I live out my fandom of cricket by being an armchair quarterback.
As such, cricket is pretty much the ideal proving ground for new skills that I learn.

I've documented some of my cricket projects [[https://medium.com/@aahaansingh][here]], along with some of my hopefully interesting findings.
My analysis is based on data from [[https://cricsheet.org/][Cricsheet]], which I process using [[https://github.com/aahaansingh/CricBase][this]] tool.

# [^fn:1]: A bit of a tortured idiom here but there's no real cricket equivalent. Umpire?



** DONE Celadon                                                 :@apps:@tech:
:PROPERTIES:
:EXPORT_FILE_NAME: proj2
:EXPORT_DATE: 2025-09-05
:END:

I'm working on an [[https://github.com/aahaansingh/Celadon/tree/main][RSS reader desktop app]] in Tauri (not a novel idea, but I'm looking to brush up on my Rust)[^fn:1]. Let this page serve as a testament to my will to actually complete it.

[^fn:1]: And I have a somewhat expansive list of feeds so I figure that it's worth customizing my experience.



** DONE Neural Net                                                :@ml:@tech:
:PROPERTIES:
:EXPORT_FILE_NAME: proj3
:EXPORT_DATE: 2025-09-05
:END:

I implemented a neural network in NumPy—I get the impression that it is a rite of passage. You can check it out [[https://github.com/aahaansingh/NeuralNet][here]]!

* Notes
:PROPERTIES:
:EXPORT_HUGO_SECTION: notes
:END:

** DONE Library                                           :@library:thoughts:
:PROPERTIES:
:EXPORT_FILE_NAME: note1
:EXPORT_DATE: 2025-09-06
:END:

In my first year of college humanities, my class was instructed to keep a commonplace book of quotes and comments for each of our assigned readings to get us thinking critically about them.
This had the effect of making the unit more interesting, but also of making the idea of keeping a commonplace book less attractive.
Still, the idea held some appeal to me.

Over the past couple of years, I have been looking for interesting blogs and websites to follow.
Everybody does this whether they're thinking about it or not, though much of the work is done by the algorithms that we are subject to.
I wanted to remove this element, because, in addition to the well-documented risks and harms of passively being fed information, it just doesn't get me anywhere interesting.
It's not very common anymore to bump into something surprising or exciting on one's daily trundles through cyberspace.
Doing so requires a bit more intentionality—leaping through hyperlinks, I suppose.

In any case, here are some interesting websites, in no particular order.

*** Tech

- [[https://www.citationneeded.news//][Citation Needed]]: I did not find crypto very interesting before this newsletter, but now I do!
  Molly White is very methodical in how she dissects the complex, tangled interests of the crypto industry, which is very important now that crypto is going mainstream.
  
- [[https://www.wheresyoured.at/][Where's Your Ed At]]: I found Ed Zitron's Substack a few months back. He has very interesting things to stay about the present state and trajectory of private-sector AI;
  over the past few months, he has been looking more and more correct.

*** Music

- [[https://thequietus.com/][The Quietus]]: I don't listen to what they push 90% of the time since they're a bit experimental for my tastes but the 10% is a very good 10%.

- [[https://compilationnation.substack.com/][Compilation Nation]]: I picked up an older Compilation Nation zine and it was very good, and this is the same thing but online.

*** Misc
- [[https://kottke.org/][Kottke]]: I don't read most of the posts on here but every so often they post something /really/ interesting and that's often how I discover a new blog.

- [[https://pudding.cool/][The Pudding]]: I don't think journalism gets much more engaging than [[https://pudding.cool/2025/04/music-dna][this]].

** DONE Call And Response                       :@call_and_response:thoughts:
:PROPERTIES:
:EXPORT_FILE_NAME: note2
:EXPORT_DATE: 2025-09-08
:END:

I feel like there has been a mismatch between the amount that I've read over the summer and what I have to "show" for it.
Generally, when somebody talks about what they've read (or wants to impress on somebody just how much they've read), they will be referring exclusively to books.
The book as a structure seems to carry with it an inherent prestige, which is warranted to a degree because being immersed in an author's universe, whether fictional or some component of the real, requires many words.
It's a similar phenomenon to how [[https://rateyourmusic.com/][RYM]] incentivizes people to listen to whole albums rather than random songs.
This is a good thing, but books are not the exclusive stores of literary or intellectual merit.

I have not read many books this
@@html:{{< sidenote "summer" >}}Though I am very proud of the fact that I completed Anna Karenina after nine months.{{< /sidenote >}}@@.
for various reasons, one of which is the fact that I have spent much of my reading time looking for blogs and interesting publications to follow.
I feel like this has been time well spent because one should read widely to some degree in addition to reading deeply, and building a good (RSS) feed enables the former.
Over the course of this search, I have found pieces that have made me think very much.
To give the articles that I find interesting due consideration, I think that it would be a good exercise to clarify my thoughts on one such article, every so often, and share
@@html:{{< sidenote "them" >}}A very pompous way of saying (to nobody) that I am going to write long comments on here rather than a comment section, but this is MY website and I can SAY WHAT I WANT!{{< /sidenote >}}@@.

My friend Arnav wrote an [[https://arnavharve.substack.com/p/how-effective-is-congress-as-an-institution][piece]] a couple of months back about the effectiveness of Congress with regard to passing impactful laws, and I thought that his analysis was really interesting.
He considers [[https://therevolvingdoorproject.org/a-brief-history-of-matt-yglesias-screwing-workers/][Matt Yglesias]] and Simon Bazelon's "[[https://www.slowboring.com/p/the-rise-and-importance-of-secret][Secret Congress]]" hypothesis that Congress actually is quite effective but that the perception of Congress's gridlock is fuelled by high-profile, partisan failures.
In short, they claim that a lot is done on issues that are not political flashpoints because they have bipartisan support, but that there are disincentives to such advances being publicized.

Arnav had a nice quick-and-dirty approach to testing the hypothesis, which involved feeding bill information into an LLM and getting it to rate bills by importance.
Thus, he found that there were more impactful bills passed than he (and I) would have believed.

*** Why Is That?

I can think of a couple of reasons which may or may not have to do with the "Secret Congress" hypothesis.
I was quite skeptical of it because legislators in the majority party have an incentive to publicize the passing of /any/ legislation, since it makes their governance seem more effective.
There is also the fact that, as Arnav pointed out, there is no real political incentive for politicians to pass legislature if it won't get them re-elected, unless you believe in politicians acting out of the goodness of their hearts.
I suggest some other reasons for these findings:
+ *Interest Groups*: Election chances aren't a direct function of how helpful the legislation that a politician supports is to the general populace, or the world would be a better place.
  I'm quite surprised that this was not brought up by Yglesias as a reason why Congress might want to keep their activities secret from the public; after all, lobbyists will stay informed regardless, and the people perhaps shouldn't be.
+ *Housekeeping*: A lot of the bills that Arnav named were mostly terminating COVID-era spending or renewing existing processes, like the debt limit raise and FAA reauthorization.
  These could be considered important in some sense, but they are more about keeping things functional; it is about the disincentives of obstructionism, not the incentives for bipartisanship.
+ *Different Strokes*: While people like Arnav and I would not have heard much about disaster relief funding, I'm sure that people who were affected (or proximate to those affected) did.
  I suspect that people take disaster relief as a given; when FEMA got cut recently, it was definitely in the news.

In any case, if we take Congress to operate in secrecy, I would think that interest groups would be the biggest reason why.
More than enabling secrecy, they incentivize it in many case so that legislators are not held accountable.
I found [[https://archive.org/details/gilens_and_page_2014_-testing_theories_of_american_politics.doc/page/n5/mode/2up][this]] interesting study that looks at the quantifiable impacts of interest groups against the will of the citizenry, and though there are clear flaws (the analysis is rather rough and it is hard to draw particular conclusions), I think it is uncontroversial to say that interest groups have an outsized impact on the legislative process.

*** Closing Thoughts

I thought this was a pretty cool idea that was thoughtfully
@@html:{{< sidenote "executed" >}}Except for the art. Japanese art has lots of ninjas, no need to generate an AI one!{{< /sidenote >}}@@.
I agree that it would be cool to find some way to track congressional productivity over time, and I would further suggest doing so by legislator.
When people talk about how productive legislators are, they focus on the number of bills rather than the impact of said bills.
While there's more to being a legislator than writing impactful legislation (because enacting change takes many forms), I think that it would be a useful method of evaluation.
I am, however, too lazy to make it happen.
